apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4 # tells deployment to run 4 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: task-pv-storage
        persistentVolumeClaim:
          claimName: task-pv-claim
      - name: nginx-config
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: site.conf
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: task-pv-storage
          mountPath: "/var/www/html"
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80 # Default port for image
  type: LoadBalancer